### ISSUE TITLE
Add image size entry to annotation file

### ISSUE THREAD

**Issue by ssedai026** [ilfrich/annotator#5]
Add image_size entry as
..
annotationType: x
shape:[]
image_size:[height, width]
..

**Comment by ilfrich** [comment]
@ssedai026:
- I have added the image size to the annotation. 
- Due to the current structure of the JSON file and to ensure backward compatibility, the `imageSize` key is added to each polygon (a lot of duplication). I didn't want to break any tool that uses the existing JSON format and parses it.
- Please also note the order: `imageSize: [width, height]`, to be consistent with all the polygon definitions `[x, y]`
- For frame sets it is assumed that all images have the same dimensions.

_Changes pushed to Git and Docker image updated_
